stages:
  - test

unit_tests:
  stage: test
  image: python:3.8
  before_script:
    - pip install --upgrade pip
    - pip install python-dotenv==1.0.1
    - pip install pytest==8.3.5
  script:
    - pytest tests/